#!/usr/bin/env python3
"""Parse JasperGold counterexample traces into cycle-indexed events.

Supported inputs:

* lightweight text traces with `cycle N: sig=value` style content
* VCD traces generated by `prove -dump_trace -dump_trace_type vcd`
"""

from __future__ import annotations

import argparse
import gzip
import json
import re
from pathlib import Path

CYCLE_RE = re.compile(
    r"(?:\b(?:cycle|time|step)\s*(?:=|:)?\s*|@)(?P<cycle>\d+)\b",
    re.IGNORECASE,
)
ASSIGN_RE = re.compile(
    r"(?P<signal>[A-Za-z_][A-Za-z0-9_.$]*(?:\[[^\]]+\])?)\s*=\s*"
    r"(?P<value>[A-Za-z0-9_'bxzBXZ.]+|0x[0-9A-Fa-f]+|true|false)"
)
PROPERTY_RE = re.compile(r"\b(?:property|assertion|cover)\s*[:=]?\s*(?P<property>[A-Za-z_][A-Za-z0-9_$:.-]+)")
VCD_VAR_RE = re.compile(
    r"^\$var\s+\S+\s+(?P<width>\d+)\s+(?P<code>\S+)\s+(?P<name>\S+)(?:\s+\S+)?\s+\$end"
)


def normalize_signal(name: str) -> str:
    if "." in name:
        return name.rsplit(".", 1)[-1]
    return name


def parse_trace(path: Path) -> dict[str, object]:
    if path.name.lower().endswith((".vcd", ".vcd.gz")):
        return parse_vcd(path)

    cycles: dict[int, dict[str, str]] = {}
    raw_events: list[str] = []
    current_cycle: int | None = None

    text = read_trace_text(path)
    property_id = infer_property_from_trace_path(path) or infer_property_from_text(text)

    for line in text.splitlines():
        cycle_match = CYCLE_RE.search(line)
        if cycle_match:
            current_cycle = int(cycle_match.group("cycle"))
            cycles.setdefault(current_cycle, {})

        assigns = ASSIGN_RE.findall(line)
        if assigns and current_cycle is not None:
            cycles.setdefault(current_cycle, {})
            for signal, value in assigns:
                cycles[current_cycle][normalize_signal(signal)] = value
            raw_events.append(line.strip())

    events = [
        {
            "cycle": cycle,
            "signals": signals,
            "changed_signals": sorted(signals),
        }
        for cycle, signals in sorted(cycles.items())
    ]

    return {
        "trace_file": str(path),
        "trace_format": "text",
        "property_id": property_id,
        "events": events,
        "raw_events": raw_events[:50],
        "parser_errors": [] if events else parser_warnings(path, text),
    }


def parse_vcd(path: Path, max_events: int = 200) -> dict[str, object]:
    code_to_signal: dict[str, str] = {}
    current_time = 0
    snapshots: dict[int, dict[str, str]] = {}
    changes_by_time: dict[int, dict[str, str]] = {}
    values: dict[str, str] = {}
    in_header = True
    scope_stack: list[str] = []
    raw_events: list[str] = []

    for raw_line in read_trace_text(path).splitlines():
        line = raw_line.strip()
        if not line:
            continue
        if line.startswith("$scope "):
            parts = line.split()
            if len(parts) >= 3:
                scope_stack.append(parts[2])
            continue
        if line.startswith("$upscope"):
            if scope_stack:
                scope_stack.pop()
            continue
        var_match = VCD_VAR_RE.match(line)
        if var_match:
            signal_name = var_match.group("name")
            if should_keep_vcd_signal(scope_stack, signal_name):
                code_to_signal[var_match.group("code")] = normalize_signal(signal_name)
            continue
        if line == "$enddefinitions $end":
            in_header = False
            snapshots.setdefault(current_time, dict(values))
            continue
        if in_header:
            continue
        if line.startswith("#"):
            try:
                current_time = int(line[1:])
            except ValueError:
                continue
            snapshots.setdefault(current_time, dict(values))
            continue
        parsed = parse_vcd_value_change(line)
        if not parsed:
            continue
        code, value = parsed
        signal = code_to_signal.get(code)
        if signal is None:
            continue
        values[signal] = value
        changes_by_time.setdefault(current_time, {})[signal] = value
        snapshots[current_time] = dict(values)
        if len(raw_events) < max_events:
            raw_events.append(line)

    events = [
        {
            "cycle": cycle,
            "signals": signals,
            "changed_signals": sorted(changes_by_time.get(cycle, {})),
            "changes": changes_by_time.get(cycle, {}),
        }
        for cycle, signals in sorted(snapshots.items())[:max_events]
    ]
    return {
        "trace_file": str(path),
        "trace_format": "vcd",
        "property_id": infer_property_from_trace_path(path),
        "signals": sorted(set(code_to_signal.values())),
        "events": events,
        "raw_events": raw_events[:50],
        "parser_errors": [] if events else parser_warnings(path, read_trace_text(path)),
    }


def parse_vcd_value_change(line: str) -> tuple[str, str] | None:
    if line[0] in "01xXzZ":
        return line[1:], line[0].lower()
    if line[0] in "bBrR":
        parts = line.split()
        if len(parts) != 2:
            return None
        return parts[1], parts[0][1:].lower()
    return None


def read_trace_text(path: Path) -> str:
    data = path.read_bytes()
    if data.startswith(b"\x1f\x8b"):
        data = gzip.decompress(data)
    return data.decode(errors="ignore")


def infer_property_from_trace_path(path: Path) -> str | None:
    name = path.name
    match = re.search(r"\.(?:properties_i|assumptions_i)\.([A-Za-z0-9_:]+)\.", name)
    if match:
        return match.group(1)
    return None


def infer_property_from_text(text: str) -> str | None:
    for line in text.splitlines()[:20]:
        match = PROPERTY_RE.search(line)
        if match:
            return match.group("property")
    return None


def parser_warnings(path: Path, text: str) -> list[dict[str, object]]:
    suspicious = [
        line.strip()
        for line in text.splitlines()
        if any(token in line.lower() for token in ["cycle", "step", "time", "trace", "error"])
    ]
    if not suspicious:
        return []
    return [
        {
            "kind": "unparsed_trace_events",
            "message": "Trace contained event-like text but no signal events were parsed.",
            "trace_file": str(path),
            "examples": suspicious[:5],
        }
    ]


def should_keep_vcd_signal(scope_stack: list[str], signal_name: str) -> bool:
    if signal_name.startswith("\\:"):
        return False
    if "properties_i" in scope_stack or "assumptions_i" in scope_stack:
        return False
    return True


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("trace", type=Path)
    parser.add_argument("--out", type=Path)
    args = parser.parse_args()

    payload = parse_trace(args.trace)
    text = json.dumps(payload, indent=2)
    if args.out:
        args.out.parent.mkdir(parents=True, exist_ok=True)
        args.out.write_text(text + "\n")
    else:
        print(text)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
