#!/usr/bin/env python3
"""Parse JasperGold counterexample traces into cycle-indexed events.

Supported inputs:

* lightweight text traces with `cycle N: sig=value` style content
* VCD traces generated by `prove -dump_trace -dump_trace_type vcd`
"""

from __future__ import annotations

import argparse
import json
import re
from pathlib import Path

CYCLE_RE = re.compile(r"\b(?:cycle|time|step)\s*(?P<cycle>\d+)\b", re.IGNORECASE)
ASSIGN_RE = re.compile(r"\b(?P<signal>[A-Za-z_][A-Za-z0-9_$]*)\s*=\s*(?P<value>[A-Za-z0-9_'bxzBXZ]+)")
VCD_VAR_RE = re.compile(
    r"^\$var\s+\S+\s+(?P<width>\d+)\s+(?P<code>\S+)\s+(?P<name>\S+)(?:\s+\S+)?\s+\$end"
)


def normalize_signal(name: str) -> str:
    if "." in name:
        return name.rsplit(".", 1)[-1]
    return name


def parse_trace(path: Path) -> dict[str, object]:
    if path.suffix.lower() == ".vcd":
        return parse_vcd(path)

    cycles: dict[int, dict[str, str]] = {}
    raw_events: list[str] = []
    current_cycle: int | None = None

    for line in path.read_text(errors="ignore").splitlines():
        cycle_match = CYCLE_RE.search(line)
        if cycle_match:
            current_cycle = int(cycle_match.group("cycle"))
            cycles.setdefault(current_cycle, {})

        assigns = ASSIGN_RE.findall(line)
        if assigns and current_cycle is not None:
            cycles.setdefault(current_cycle, {})
            for signal, value in assigns:
                cycles[current_cycle][signal] = value
            raw_events.append(line.strip())

    events = [
        {
            "cycle": cycle,
            "signals": signals,
        }
        for cycle, signals in sorted(cycles.items())
    ]

    return {
        "trace_file": str(path),
        "trace_format": "text",
        "events": events,
        "raw_events": raw_events[:50],
    }


def parse_vcd(path: Path, max_events: int = 200) -> dict[str, object]:
    code_to_signal: dict[str, str] = {}
    current_time = 0
    snapshots: dict[int, dict[str, str]] = {}
    values: dict[str, str] = {}
    in_header = True

    for raw_line in path.read_text(errors="ignore").splitlines():
        line = raw_line.strip()
        if not line:
            continue
        var_match = VCD_VAR_RE.match(line)
        if var_match:
            code_to_signal[var_match.group("code")] = normalize_signal(var_match.group("name"))
            continue
        if line == "$enddefinitions $end":
            in_header = False
            snapshots.setdefault(current_time, dict(values))
            continue
        if in_header:
            continue
        if line.startswith("#"):
            try:
                current_time = int(line[1:])
            except ValueError:
                continue
            snapshots.setdefault(current_time, dict(values))
            continue
        parsed = parse_vcd_value_change(line)
        if not parsed:
            continue
        code, value = parsed
        signal = code_to_signal.get(code)
        if signal is None:
            continue
        values[signal] = value
        snapshots[current_time] = dict(values)

    events = [
        {
            "cycle": cycle,
            "signals": signals,
        }
        for cycle, signals in sorted(snapshots.items())[:max_events]
    ]
    return {
        "trace_file": str(path),
        "trace_format": "vcd",
        "signals": sorted(set(code_to_signal.values())),
        "events": events,
    }


def parse_vcd_value_change(line: str) -> tuple[str, str] | None:
    if line[0] in "01xXzZ":
        return line[1:], line[0].lower()
    if line[0] in "bBrR":
        parts = line.split()
        if len(parts) != 2:
            return None
        return parts[1], parts[0][1:].lower()
    return None


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("trace", type=Path)
    parser.add_argument("--out", type=Path)
    args = parser.parse_args()

    payload = parse_trace(args.trace)
    text = json.dumps(payload, indent=2)
    if args.out:
        args.out.parent.mkdir(parents=True, exist_ok=True)
        args.out.write_text(text + "\n")
    else:
        print(text)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
